{
	"PackageVulnerabilityID": 1,
	"DisclosureDate": "2020-08-10",
	"AffectedVersionRange": "*",
	"Summary": "Arbitrary Code Execution",
	"Author": {
		"Username": "",
		"Name": ""
	},
	"Package": {
		"Registry": "pip",
		"Name": "django-make-app",
		"URL": "https://pypi.org/project/django-make-app",
		"Downloads": "29743"
	},
	"CWEs": [{
		"ID": "CWE-94",
		"Description": ""
	}],
	"CVSS": {
		"Version": "3.1",
		"AV": "N",
		"AC": "L",
		"PR": "N",
		"UI": "N",
		"S": "U",
		"C": "H",
		"I": "H",
		"A": "H",
		"E": "",
		"RL": "",
		"RC": "",
		"Score": "9.8"
	},
	"CVEs": [
		"CVE-2017-16764"
	],
	"Repository": {
		"URL": "https://github.com/illagrenan/django-make-app",
		"Codebase": [
			"Python"
		]
	},
	"Permalinks": [],
	"References": [{
			"Description": "nvd.nist.gov",
			"URL": "https://nvd.nist.gov/vuln/detail/CVE-2017-16764"
		},
		{
			"Description": "GitHub Issue",
			"URL": "https://github.com/illagrenan/django-make-app/issues/5"
		}
	]
}